version: '3.1'
services:
  web:
    image: depotix:local
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - depotix-web-data:/var/lib/depotix
    environment:
      - DEPOTIX_RC=/etc/depotix/depotix.conf
      - HOST=db
      - USER=depotix
      - PASSWORD=depotixdb2024
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=depotixdb2024
      - POSTGRES_USER=depotix
    volumes:
      - depotix-db-data:/var/lib/postgresql/data

volumes:
  depotix-web-data:
  depotix-db-data:

