version: "3.9"
services:
  web:
    build: { context: .., dockerfile: ui/Dockerfile }
    env_file: .env
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    depends_on: [api]
    restart: unless-stopped
    networks: [appnet]

  api:
    build: { context: .., dockerfile: api/Dockerfile }
    env_file: .env
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DATABASE_URL: ${DATABASE_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      TZ: ${TZ}
    restart: unless-stopped
    networks: [appnet]

  caddy:
    image: caddy:2
    depends_on: [web, api]
    ports: ["80:80","443:443"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks: [appnet]

networks: { appnet: {} }
volumes: { caddy_data: {}, caddy_config: {} }
