# Generated by Django 5.0.8 on 2025-09-11 13:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_documentsequence_salesorder_invoice_salesorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='abv_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alkoholgehalt % vol', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='beverage_type',
            field=models.CharField(blank=True, choices=[('water', 'Wasser'), ('softdrink', 'Softdrink'), ('beer', 'Bier'), ('wine', 'Wein'), ('spirits', 'Spirituose'), ('energy', 'Energy Drink'), ('juice', 'Saft'), ('other', 'Sonstiges')], help_text='Getränkeart', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(blank=True, help_text='Marke/Hersteller', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='container_type',
            field=models.CharField(blank=True, choices=[('glass', 'Glasflasche'), ('pet', 'PET'), ('can', 'Dose'), ('crate', 'Kiste/Tray'), ('keg', 'Fass/Keg')], help_text='Gebindeart', max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='country_of_origin',
            field=models.CharField(blank=True, help_text='ISO-2 Landescode, z. B. CH', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='deposit_chf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pfand in CHF', max_digits=6),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='ean_pack',
            field=models.CharField(blank=True, help_text='EAN Packung', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='ean_unit',
            field=models.CharField(blank=True, help_text='EAN Einzelgebinde', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_alcoholic',
            field=models.BooleanField(default=False, help_text='Alkoholisch'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='is_returnable',
            field=models.BooleanField(default=False, help_text='Mehrweg/Rücknahme'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.10'), help_text='MwSt. %', max_digits=4),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='volume_ml',
            field=models.PositiveIntegerField(blank=True, help_text='Füllmenge je Einheit in ml', null=True),
        ),
    ]
