# Generated by Django 5.0.8 on 2025-09-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_documentsequence_salesorder_invoice_salesorderitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('LS', 'Sales Order'), ('INV', 'Invoice')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='documentsequence',
            index=models.Index(fields=['document_type', 'year'], name='inventory_d_documen_5beca2_idx'),
        ),
    ]
