# Generated by Django 5.0.8 on 2025-09-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_abv_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='beverage_type',
            field=models.CharField(blank=True, choices=[('water', 'Wasser'), ('softdrink', 'Softdrink'), ('beer', 'Bier'), ('wine', 'Wein'), ('spirits', 'Spirituose'), ('energy', 'Energy Drink'), ('juice', 'Saft'), ('other', 'Sonstiges')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='container_type',
            field=models.CharField(blank=True, choices=[('glass', 'Glasflasche'), ('pet', 'PET'), ('can', 'Dose'), ('crate', 'Kiste/Tray'), ('keg', 'Fass/Keg')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='ean_pack',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='ean_unit',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='is_alcoholic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=8.1, help_text='MwSt. %', max_digits=4),
        ),
    ]
