# Generated by Django 5.1.2 on 2025-09-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(max_length=20, unique=True, null=True, blank=True),
        ),
    ]