# Generated by Django 5.1.2 on 2025-09-19 11:05

from django.db import migrations


def assign_customer_numbers(apps, schema_editor):
    Customer = apps.get_model('inventory', 'Customer')
    customers = Customer.objects.all().order_by('id')

    for i, customer in enumerate(customers, start=1000):
        customer.customer_number = str(i)
        customer.save()


def reverse_customer_numbers(apps, schema_editor):
    Customer = apps.get_model('inventory', 'Customer')
    Customer.objects.update(customer_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_customer_customer_number'),
    ]

    operations = [
        migrations.RunPython(assign_customer_numbers, reverse_customer_numbers),
    ]