# Generated by Django 5.0.8 on 2025-10-02 08:48

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_idempotency_and_constraints'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockmovement',
            name='stockmov_user_time_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='inventory_s_item_id_e3c2c2_idx',
            old_name='stockmov_item_type_time_idx',
        ),
        # Skip is_archived - it already exists in the database
        # migrations.AddField(
        #     model_name='invoice',
        #     name='is_archived',
        #     field=models.BooleanField(default=False, help_text='Whether this invoice is archived'),
        # ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Lieferdatum', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_number',
            field=models.CharField(blank=True, help_text='4-stellige Kundennummer (ab 1000)', max_length=4, null=True, unique=True, validators=[inventory.models.validate_customer_number]),
        ),
        # Skip is_archived index - it already exists
        # migrations.AddIndex(
        #     model_name='invoice',
        #     index=models.Index(fields=['is_archived'], name='inventory_i_is_arch_9d6f13_idx'),
        # ),
    ]
